export function formatMvpChecklist(): string {
  return [
    "COSIA MVP Acceptance Checklist",
    "",
    "Provider roles:",
    "- mock: regression only; not a production readiness signal",
    "- codex-cli: required MVP acceptance provider via Codex OAuth",
    "- openrouter/openai-compatible: optional provider acceptance",
    "",
    "[ ] 1. Environment and build",
    "    Command:",
    "      node --version",
    "      npm --version",
    "      npm install",
    "      npm run build",
    "    Expected:",
    "      Node.js is 24 or newer.",
    "      Build completes without TypeScript errors.",
    "",
    "[ ] 2. Policy and provider",
    "    Command:",
    "      cosia policy check --repair",
    "      cosia provider check codex-cli",
    "    Expected:",
    "      POLICY.json and POLICY.md are ok.",
    "      codex-cli provider status is ok.",
    "",
    "[ ] 3. Workspace bootstrap",
    "    Command:",
    "      cosia init",
    "      cosia agent list",
    "      cosia session create --goal \"MVP acceptance session\"",
    "      cosia session list",
    "    Expected:",
    "      A default cosia-agent exists.",
    "      A new active session is created and assigned to the default agent.",
    "",
    "[ ] 4. Runtime smoke with Codex OAuth",
    "    Command:",
    "      cosia run --session <session-id> --provider codex-cli --prompt \"현재 세션 목표를 요약해줘.\"",
    "    Expected:",
    "      A normal final answer is printed.",
    "      No Provider failed message appears.",
    "",
    "[ ] 5. Observation discipline",
    "    Command:",
    "      cosia run --session <session-id> --provider codex-cli --require-tools --prompt \"현재 구현 상태를 실제 파일을 보고 요약해줘.\"",
    "      cosia policy audit --session <session-id> --latest-run --limit 10",
    "    Expected:",
    "      The run completes after at least one observation tool call.",
    "      Audit output records tool_decision events.",
    "",
    "[ ] 6. Memory workflow",
    "    Command:",
    "      cosia memory add --tier core --kind decision --content \"COSIA MVP acceptance uses codex-cli as required provider.\" --importance 5 --confidence 0.9",
    "      cosia memory search --query \"required provider\" --show-score",
    "      cosia memory candidate list",
    "    Expected:",
    "      The added core memory appears in search results.",
    "      Candidate list remains readable even when empty.",
    "",
    "[ ] 7. Skill workflow",
    "    Command:",
    "      cosia skill list",
    "      cosia skill select --agent cosia-agent --prompt \"git commit 규칙을 참고해줘\" --explain",
    "    Expected:",
    "      Global skills can be listed.",
    "      Skill selection explanation uses deterministic score columns.",
    "",
    "[ ] 8. Review inbox",
    "    Command:",
    "      cosia review",
    "      cosia review --memory",
    "      cosia review --skill",
    "      cosia chat --session <session-id> --provider codex-cli",
    "      # inside chat: /review",
    "    Expected:",
    "      Review queue prints a compact table or a clear empty state.",
    "      Review commands show temporary indexes and stable id prefixes.",
    "",
    "[ ] 9. Context maintenance",
    "    Command:",
    "      cosia session summarize <session-id> --from-context --provider codex-cli",
    "      cosia session context status <session-id>",
    "      cosia session context compact <session-id> --keep-last 3 --reason \"MVP context maintenance test\"",
    "    Expected:",
    "      Summary preview is printed without writing unless --yes is used.",
    "      Context status reports run counts and summary placeholder state.",
    "      Compact preview reports kept and archived run counts.",
    "",
    "[ ] 10. Regression checks",
    "    Command:",
    "      npm run typecheck",
    "      npm test",
    "      npm run build",
    "      cosia policy check --repair",
    "    Expected:",
    "      All commands complete successfully.",
    "",
    "[ ] 11. Optional provider",
    "    Command:",
    "      cosia provider check openrouter",
    "    Expected:",
    "      If configured, openrouter reports ok.",
    "      If disabled or missing an API key, it fails with a clear reason and hint."
  ].join("\n");
}
