import { existsSync, readFileSync, writeFileSync } from "node:fs";
import type { AgentManifest } from "../types.js";
import { normalizeNewlines } from "./skill_text.js";
import type { SkillRecord } from "./skill_store.js";
import { SkillStore } from "./skill_store.js";

export type SkillCheckResult = {
  ok: boolean;
  scope: "global" | "agent";
  agentId?: string;
  mirrorExists: boolean;
  mirrorMatches: boolean;
  repaired: boolean;
  missingSkillFiles: string[];
  missingMetadataFiles: string[];
  orphanSkillFiles: string[];
  manualOnlySkills: string[];
  missingPreferredSkills: string[];
  missingBlockedSkills: string[];
};

export class SkillMirror {
  constructor(private readonly store: SkillStore) {}

  ensureGlobalMirror(): void {
    this.store.ensureSkillsDir();
    const indexPath = this.store.globalSkillsIndexPath();
    if (!existsSync(indexPath)) {
      this.syncSkillsIndex();
    }
  }

  syncSkillsIndex(agentId?: string): string {
    if (agentId) {
      const manifest = this.store.readAgentManifest(agentId);
      const path = this.store.agentSkillsIndexPath(agentId);
      writeFileSync(path, renderAgentSkillsIndex(agentId, manifest, this.store.readSkillRecords()), "utf8");
      return path;
    }
    writeFileSync(this.store.globalSkillsIndexPath(), renderGlobalSkillsIndex(this.store.readSkillRecords()), "utf8");
    return this.store.globalSkillsIndexPath();
  }

  checkSkills(agentId?: string, repair = false): SkillCheckResult {
    this.store.ensureSkillsDir();
    const skills = this.store.readSkillRecords();
    const metadataIds = new Set(skills.map((skill) => skill.id));
    const mdIds = new Set(this.store.readSkillMarkdownIds());
    const missingSkillFiles = skills.filter((skill) => !mdIds.has(skill.id)).map((skill) => skill.id);
    const orphanSkillFiles = [...mdIds].filter((skillId) => !metadataIds.has(skillId)).sort();
    const missingMetadataFiles = orphanSkillFiles;
    const manualOnlySkills = skills.filter((skill) => skill.triggers.length === 0).map((skill) => skill.id);
    const manifest = agentId ? this.store.readAgentManifest(agentId) : undefined;
    const missingPreferredSkills = manifest ? manifest.preferredSkills.filter((skillId) => !metadataIds.has(skillId)).sort() : [];
    const missingBlockedSkills = manifest ? manifest.blockedSkills.filter((skillId) => !metadataIds.has(skillId)).sort() : [];
    const mirrorPath = agentId ? this.store.agentSkillsIndexPath(agentId) : this.store.globalSkillsIndexPath();
    const expectedMirror = agentId
      ? renderAgentSkillsIndex(agentId, manifest!, skills)
      : renderGlobalSkillsIndex(skills);
    const mirrorExists = existsSync(mirrorPath);
    let mirrorMatches = mirrorExists && normalizeNewlines(readFileSync(mirrorPath, "utf8")) === normalizeNewlines(expectedMirror);
    let repaired = false;
    if (repair && !mirrorMatches) {
      writeFileSync(mirrorPath, expectedMirror, "utf8");
      mirrorMatches = true;
      repaired = true;
    }
    return {
      ok: mirrorMatches && missingSkillFiles.length === 0 && missingPreferredSkills.length === 0 && missingBlockedSkills.length === 0,
      scope: agentId ? "agent" : "global",
      agentId,
      mirrorExists,
      mirrorMatches,
      repaired,
      missingSkillFiles,
      missingMetadataFiles,
      orphanSkillFiles,
      manualOnlySkills,
      missingPreferredSkills,
      missingBlockedSkills
    };
  }
}

export function renderGlobalSkillsIndex(skills: SkillRecord[]): string {
  const body = skills.length
    ? skills.map((skill) => {
        const triggers = skill.triggers.length ? skill.triggers.join(", ") : "manual-only";
        return `- ${skill.id} (${skill.riskLevel}; triggers: ${triggers}) - ${skill.name}`;
      }).join("\n")
    : "No promoted skills.";
  return `# SKILLS

This file is generated by COSIA from \`skills/*.json\` and \`skills/*.md\`.
Do not manually edit sections here; update skill files or run \`cosia skill sync\`.

${body}
`;
}

export function renderAgentSkillsIndex(agentId: string, manifest: AgentManifest, skills: SkillRecord[]): string {
  const skillMap = new Map(skills.map((skill) => [skill.id, skill]));
  const preferred = manifest.preferredSkills.length
    ? manifest.preferredSkills.map((skillId) => `- ${skillId}${manifest.skillWeights?.[skillId] ? ` (weight: ${manifest.skillWeights[skillId]})` : ""}`).join("\n")
    : "No preferred skills.";
  const blocked = manifest.blockedSkills.length
    ? manifest.blockedSkills.map((skillId) => `- ${skillId}`).join("\n")
    : "No blocked skills.";
  const available = skills.length
    ? skills.map((skill) => {
        const state = manifest.blockedSkills.includes(skill.id)
          ? "blocked"
          : manifest.preferredSkills.includes(skill.id)
            ? "preferred"
            : "available";
        const triggers = skill.triggers.length ? skill.triggers.join(", ") : "manual-only";
        return `- ${skill.id} [${state}] triggers: ${triggers}`;
      }).join("\n")
    : "No global skills.";
  const missingPreferred = manifest.preferredSkills.filter((skillId) => !skillMap.has(skillId));
  const missing = missingPreferred.length ? `\n\n## Missing References\n\n${missingPreferred.map((skillId) => `- ${skillId}`).join("\n")}\n` : "";
  return `# SKILLS

This file is generated by COSIA as an agent preference view over the global skill toolbox.
Agent: ${agentId}

## Preferred Skills

${preferred}

## Blocked Skills

${blocked}

## Global Skills

${available}${missing}`;
}
